# Numpy operations 

In [3]:
import numpy as np

In [13]:
arr=np.arange(0,11)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [23]:
arr/arr # it will give a warning instead of a zero erro, and replace the error place with... nan (not a number)

C:\Users\Lost Mian\AppData\Local\Temp\ipykernel_5684\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [25]:
1/arr # replave error place with the inf(infinity)

C:\Users\Lost Mian\AppData\Local\Temp\ipykernel_5684\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

* to use the numpy function we defined it as --- np.function_name(array_name)

In [51]:
np.sqrt(arr) 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [53]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [55]:
arr.var() # varience

10.0

In [57]:
arr.std() # standard deviation

3.1622776601683795

In [61]:
arr.meann() # mean

5.0

* numpy operations with 2D arrays

arr2d=np.arange(0,25).reshape(5,5)

In [76]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
arr2d+arr2d

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [82]:
arr2d.sum() # giving the sum of all the elements

300

In [86]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [88]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

# --------  Done with the Numpy operations  --------

* for more operation and functions with NumPy visit numpy.org