   # NumPy 

* functions in numpy


  

In [8]:
import numpy as np

In [10]:
mylist=[2,4,6,8]

In [12]:
mylist

[2, 4, 6, 8]

In [14]:
type(mylist)

list

In [16]:
myarray= np.array(mylist) #-- Transformation of simple list into numpy array --#

In [18]:
mylist

[2, 4, 6, 8]

In [20]:
type(myarray)

numpy.ndarray

In [22]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [24]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
mymatrix=np.array(matrix) 

In [27]:
mymatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
type(mymatrix)

numpy.ndarray

In [29]:
mymatrix[1][2]

6

In [30]:
matrix[1][2]

6

In [31]:
np.arange(0,15,4) #--  defining a numpy array directly --#

array([ 0,  4,  8, 12])

In [32]:
np.zeros((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [34]:
np.linspace(0,15,3) #--  to linearly space the list items --#

array([ 0. ,  7.5, 15. ])

In [35]:
np.eye(4, dtype=int) # numpy identity matrix function .eye() #

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [36]:
np.random.rand(5,2 )

array([[0.24801924, 0.11864614],
       [0.30835968, 0.94435666],
       [0.78196738, 0.70273052],
       [0.0767214 , 0.16736055],
       [0.39517903, 0.40269814]])

In [37]:
np.random.randn(5,2 )

array([[ 2.36935108, -0.30554994],
       [ 0.07518616,  0.1682361 ],
       [-0.69212315,  1.30004578],
       [ 0.46362915, -0.91517944],
       [-0.68688023,  0.0258184 ]])

In [38]:
np.random.randint(0,101,10) # -- third argument is the no. of random items you want --#

array([48, 57, 28, 10,  2, 83, 49, 74, 34, 71])

In [39]:
np.random.randint(1,300,(2,3))

array([[ 25, 169,  72],
       [ 38,  78, 116]])

In [40]:
np.random.seed(101)
np.random.rand(2,4,3)

array([[[0.51639863, 0.57066759, 0.02847423],
        [0.17152166, 0.68527698, 0.83389686],
        [0.30696622, 0.89361308, 0.72154386],
        [0.18993895, 0.55422759, 0.35213195]],

       [[0.1818924 , 0.78560176, 0.96548322],
        [0.23235366, 0.08356143, 0.60354842],
        [0.72899276, 0.27623883, 0.68530633],
        [0.51786747, 0.04848454, 0.13786924]]])

In [41]:
np.random.seed(42)           # seting a seed value with seed function give the same value each time in random function
np.random.rand(2,3)


array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [42]:
arr=np.arange(0,30)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [44]:
arr.reshape(6,5)  # reshape funciton shapes the array in a matrix like form of given order

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [45]:
ranarr= np.random.randint(0,101,10) 

In [46]:
ranarr

array([74, 74, 87, 99, 23,  2, 21, 52,  1, 87])

In [47]:
ranarr.max()

99

In [48]:
ranarr.argmax()

3

In [49]:
ranarr.min()

1

In [50]:
ranarr.argmin()

8

In [99]:
ranarr.dtype

dtype('int32')

In [101]:
arr.shape

(30,)

In [103]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [107]:
arrrn=arr.reshape(1,30)

In [110]:
arrrn

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [112]:
arrrn.shape

(1, 30)